name: Tacos CICD

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - 00-start

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Installing Node.js'

  - script: |
      npm install
      npm run build -- --prod
    displayName: 'Running npm install and build for prod'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/dist/tacos-ui'
      contents: |
        **/*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      overWrite: true
    displayName: 'Copying built static files'

  - task: PublishBuildArtifacts@1
